config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_config:
    src: emacs.d/config
    dst: ~/.emacs.d/config
  f_init.el:
    src: emacs.d/init.el
    dst: ~/.emacs.d/init.el
  d_snippets:
    src: emacs.d/snippets
    dst: ~/.emacs.d/snippets
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_terminator:
    src: config/terminator
    dst: ~/.config/terminator
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
profiles:
  pedro-barbosa:
    dotfiles:
    - d_config
    - f_init.el
    - d_snippets
    - f_zshrc
    - d_rofi
    - d_terminator
    - f_p10k.zsh

