;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	corfu-next
	corfu-quit
	cua-copy-region
	cua-paste
	ignore-preserving-kill-region
	lsp-find-definition-mouse
	mouse-drag-tab-line
	mouse-set-region
	))

(setq mc/cmds-to-run-once
      '(
	corfu-quit
	cua-copy-handler
	handle-switch-frame
	indent-for-tab-command
	lsp-find-definition-mouse
	lsp-ui-doc--handle-mouse-movement
	mouse-set-region
	move-text-up
	))
